from __future__ import annotations


def render_web_app_html() -> str:
    return """<!doctype html>
<html><head>
<meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>
<title>Nexus Trader V16</title>
<script src='https://cdn.plot.ly/plotly-2.35.2.min.js'></script>
<style>
@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;600&family=Space+Grotesk:wght@400;600;700&display=swap');
:root{--bg:#061218;--panel:#0c1d24ee;--line:#9fcbd629;--text:#eef6fa;--muted:#9cb5bf;--gold:#f0b54f;--bull:#1fcb81;--bear:#ff6b5d}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 14% 18%,#f0b54f1f,transparent 20%),radial-gradient(circle at 85% 16%,#66bbff22,transparent 22%),linear-gradient(160deg,#051017,#08161d 48%,#041118);color:var(--text);font-family:'Space Grotesk',sans-serif}
#app{max-width:1500px;margin:0 auto;padding:18px;display:grid;gap:14px}.p{background:var(--panel);border:1px solid var(--line);border-radius:20px;padding:16px;box-shadow:0 18px 50px #0007}.g{display:grid;gap:10px}.hero{grid-template-columns:1.4fr .9fr}.controls{grid-template-columns:repeat(7,minmax(0,1fr))}.metrics{grid-template-columns:repeat(6,minmax(0,1fr))}.main{grid-template-columns:1.5fr .95fr}.split{grid-template-columns:1fr 1fr}.chips{grid-template-columns:repeat(4,minmax(0,1fr))}.minis{grid-template-columns:repeat(2,minmax(0,1fr))}
.row{display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap}.title{font-size:clamp(30px,5vw,52px);line-height:.95;letter-spacing:-.05em;margin:0}.eyebrow,.lbl{font-size:11px;letter-spacing:.18em;text-transform:uppercase;color:var(--gold)}.muted,.tiny{color:var(--muted)}.tiny{font-size:12px;line-height:1.45}.val{font-size:22px;font-weight:700;line-height:1}.clock{font-family:'IBM Plex Mono',monospace;text-align:right}.badge,.card{background:#ffffff08;border:1px solid var(--line);border-radius:16px;padding:12px}.badge{border-radius:999px;font-size:13px}.tbl{width:100%;border-collapse:collapse;font-size:13px}.tbl td,.tbl th{text-align:left;padding:8px 6px;border-bottom:1px solid #9fcbd61a}.list{display:grid;gap:8px;max-height:340px;overflow:auto}.item{border:1px solid #9fcbd624;border-radius:14px;padding:10px 12px;background:#ffffff05}.mono{font-family:'IBM Plex Mono',monospace}
select,input,textarea,button{width:100%;min-height:42px;border-radius:12px;border:1px solid #9fcbd633;background:#031019cc;color:var(--text);padding:10px 12px;font:inherit}textarea{min-height:74px;resize:vertical}button{cursor:pointer;background:linear-gradient(135deg,#f0b54f33,#1fcb8129)}#chart{min-height:560px}.warn{padding:12px 14px;border-radius:14px;border:1px solid #f0b54f44;background:#f0b54f1a;color:#ffe2aa}.status{padding:12px 14px;border-radius:14px;border:1px solid var(--line);background:#ffffff06;color:var(--muted);font-size:13px}
@media(max-width:1180px){.hero,.main,.split{grid-template-columns:1fr}.controls{grid-template-columns:repeat(2,minmax(0,1fr))}.metrics{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:760px){#app{padding:12px}.chips,.metrics,.controls,.minis{grid-template-columns:1fr}#chart{min-height:380px}}
</style></head><body>
<div id='app'>
<section class='p g hero'>
  <div class='g'>
    <div class='eyebrow'>Nexus Trader V16</div>
    <div class='row'><div><h1 class='title'>15-Minute Future Simulator</h1><div class='muted'>The simulator refreshes every 5 minutes, but the decision horizon stays anchored to 15 minutes.</div></div><div class='clock'><div id='time' class='val'>--:--:--</div><div id='date' class='tiny'>Waiting for local time</div><div id='next' class='tiny'>Next refresh in --s</div></div></div>
    <div class='g chips'>
      <div class='card'><div class='lbl'>Current Price</div><div id='m-price' class='val'>-</div><div class='tiny'>Live tape</div></div>
      <div class='card'><div class='lbl'>15m Direction</div><div id='m-dir' class='val'>-</div><div id='m-dir-sub' class='tiny'>Consensus path</div></div>
      <div class='card'><div class='lbl'>Confidence Tier</div><div id='m-tier' class='val'>-</div><div id='m-tier-sub' class='tiny'>Waiting for first run</div></div>
      <div class='card'><div class='lbl'>SQT Status</div><div id='m-sqt' class='val'>-</div><div id='m-sqt-sub' class='tiny'>Rolling quality</div></div>
    </div>
  </div>
  <div class='g'>
    <div class='g' style='grid-template-columns:1fr 1fr 1fr'><div class='badge'><strong id='b-sym'>XAUUSD</strong> market</div><div class='badge'><strong id='b-prov'>LM Studio</strong> route</div><div class='badge'><strong id='b-mode'>Frequency</strong> mode</div></div>
    <div id='eci' class='warn'>Economic calendar display waiting for first payload.</div>
    <div id='status' class='status'>Loading V16 simulator...</div>
  </div>
</section>
<section class='g controls p'>
  <div><div class='lbl'>Instrument</div><select id='symbol'><option value='XAUUSD' selected>XAUUSD</option><option value='EURUSD'>EURUSD</option><option value='BTCUSD'>BTCUSD</option></select></div>
  <div><div class='lbl'>Mode</div><select id='mode'><option value='frequency' selected>Frequency</option><option value='precision'>Precision</option></select></div>
  <div><div class='lbl'>LLM Provider</div><select id='provider'><option value='lm_studio' selected>LM Studio</option><option value='ollama'>Ollama</option><option value='nvidia_nim'>NVIDIA NIM</option></select></div>
  <div><div class='lbl'>Model Override</div><input id='model' placeholder='moonshotai/kimi-k2-instruct'></div>
  <div><div class='lbl'>Refresh Seconds</div><select id='refresh'><option value='15'>15</option><option value='30' selected>30</option><option value='60'>60</option></select></div>
  <div><div class='lbl'>Auto Refresh</div><select id='auto'><option value='on' selected>On</option><option value='off'>Off</option></select></div>
  <div><div class='lbl'>Run</div><button id='run'>Refresh Simulator</button></div>
</section>
<section class='g metrics'>
  <div class='p'><div class='lbl'>CABR Proxy</div><div id='cabr' class='val'>-</div><div class='tiny'>Branch ranking strength</div></div>
  <div class='p'><div class='lbl'>BST Survival</div><div id='bst' class='val'>-</div><div class='tiny'>Perturbation stability</div></div>
  <div class='p'><div class='lbl'>CPM Score</div><div id='cpm' class='val'>-</div><div class='tiny'>Display-only predictability</div></div>
  <div class='p'><div class='lbl'>Cone Width</div><div id='cone' class='val'>-</div><div class='tiny'>Average 15m width</div></div>
  <div class='p'><div class='lbl'>Suggested Lot</div><div id='lot' class='val'>-</div><div class='tiny'>Equity-scaled sizing</div></div>
  <div class='p'><div class='lbl'>Execution Rule</div><div id='exec' class='val'>-</div><div id='exec-sub' class='tiny'>Mode plus SQT state</div></div>
</section>
<section class='g main'>
  <div class='p g'><div class='row'><div><h2>Live Chart + Cone</h2><div class='muted'>Candles, 15-minute consensus path, cone band, minority scenario, and paper-trade markers on one chart.</div></div><div class='g' style='grid-template-columns:1fr 1fr 1fr'><div class='badge'><strong id='chart-tier'>-</strong> tier</div><div class='badge'><strong id='chart-hit'>-</strong> cone hits</div><div class='badge'><strong>5m</strong> cadence</div></div></div><div id='chart'></div></div>
  <div class='p g'>
    <div><h2>Paper Trading</h2><div class='muted'>Manual paper trades sit on top of the simulator. Lot size scales with account equity and is capped by leverage.</div></div>
    <div class='g minis'><div class='card'><div class='lbl'>Balance</div><div id='pb' class='val'>-</div></div><div class='card'><div class='lbl'>Equity</div><div id='pe' class='val'>-</div></div><div class='card'><div class='lbl'>Realized PnL</div><div id='pr' class='val'>-</div></div><div class='card'><div class='lbl'>Unrealized PnL</div><div id='pu' class='val'>-</div></div></div>
    <div class='g split'><div><div class='lbl'>Direction</div><select id='tdir'><option value='BUY'>BUY</option><option value='SELL'>SELL</option></select></div><div><div class='lbl'>Leverage</div><select id='tlev'><option value='50'>1:50</option><option value='100'>1:100</option><option value='200' selected>1:200</option></select></div></div>
    <div class='g split'><div><div class='lbl'>Stop Pips</div><input id='tstop' type='number' min='1' step='1' value='20'></div><div><div class='lbl'>Take Profit Pips</div><input id='ttp' type='number' min='1' step='1' value='30'></div></div>
    <div><div class='lbl'>Note</div><textarea id='tnote' placeholder='Why this manual paper trade exists'></textarea></div>
    <div class='g split'><button id='open'>Open Paper Trade</button><button id='reset'>Reset Paper Account</button></div>
    <div style='overflow:auto'><table class='tbl'><thead><tr><th>ID</th><th>Side</th><th>Lot</th><th>Entry</th><th>PnL</th><th></th></tr></thead><tbody id='open-body'></tbody></table></div>
  </div>
</section>
<section class='g split'>
  <div class='p g'><h2>Recent Simulations</h2><div class='muted'>Direction hit, cone hit rate, tier, and minority rescue context.</div><div id='sims' class='list'></div></div>
  <div class='p g'><h2>Closed Trade History</h2><div class='muted'>Basic PnL history for manual testing.</div><div style='overflow:auto'><table class='tbl'><thead><tr><th>Time</th><th>Symbol</th><th>Side</th><th>Lot</th><th>PnL</th></tr></thead><tbody id='closed-body'></tbody></table></div></div>
</section>
<section class='g split'>
  <div class='p g'><h2>Judge + Context</h2><div id='judge' class='list'></div></div>
  <div class='p g'><h2>News + Crowd</h2><div id='feeds' class='list'></div></div>
</section>
<script>
const st={symbol:'XAUUSD',mode:'frequency',provider:'lm_studio',model:'',sim:null,mon:null,paper:null,timer:null};
const $=(id)=>document.getElementById(id),pct=(v)=>v==null||Number.isNaN(Number(v))?'-':`${(Number(v)*100).toFixed(1)}%`,price=(v)=>v==null||Number.isNaN(Number(v))?'-':Number(v).toFixed(2),sgn=(v)=>v==null||Number.isNaN(Number(v))?'-':`${Number(v)>=0?'+':''}${Number(v).toFixed(2)}`;
const tm=(v)=>{if(!v)return'-';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString();};
const stat=(m)=>$('status').textContent=m;
function color(d){d=String(d||'').toUpperCase();if(d==='BUY'||d==='BULLISH')return'var(--bull)';if(d==='SELL'||d==='BEARISH')return'var(--bear)';return'var(--gold)';}
function tick(){const n=new Date(),nx=new Date(n);nx.setSeconds(0,0);const mod=n.getMinutes()%5;nx.setMinutes(n.getMinutes()+(mod===0?5:5-mod));$('time').textContent=n.toLocaleTimeString();$('date').textContent=n.toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric',year:'numeric'});$('next').textContent=`Next refresh in ${Math.max(0,Math.floor((nx-n)/1000))}s`;}
async function j(url,opt){const r=await fetch(url,opt);if(!r.ok){const t=await r.text();throw new Error(t||`Request failed with ${r.status}`);}return r.json();}
function head(){const sim=st.sim||{},m=sim.market||{},v=((sim.v16||{}).simulation||sim.simulation||{}),s=sim.sqt||{};$('m-price').textContent=price(m.current_price);$('m-dir').textContent=String(v.direction||'-');$('m-dir').style.color=color(v.direction);$('m-dir-sub').textContent=`${String(st.mode).toUpperCase()} mode`;$('m-tier').textContent=String(v.confidence_tier||'-').replace('_',' ').toUpperCase();$('m-tier').style.color=v.tier_color||'var(--gold)';$('m-tier-sub').textContent=v.tier_label||'No tier label';$('m-sqt').textContent=String(s.label||v.sqt_label||'-');$('m-sqt').style.color=color(String(s.label||'').toUpperCase()==='COLD'?'SELL':'BUY');$('m-sqt-sub').textContent=`Rolling accuracy ${pct(s.rolling_accuracy||v.sqt_accuracy)}`;$('b-sym').textContent=st.symbol;$('b-prov').textContent=st.provider==='nvidia_nim'?'NVIDIA NIM':st.provider==='ollama'?'Ollama':'LM Studio';$('b-mode').textContent=String(st.mode).replace(/^./,(c)=>c.toUpperCase());$('eci').textContent=(sim.eci||{}).note||'Economic calendar display is neutral.';$('chart-tier').textContent=String(v.confidence_tier||'-').replace('_',' ').toUpperCase();$('chart-tier').style.color=v.tier_color||'var(--gold)';const rec=((st.mon||{}).recent_simulations||[]).filter((x)=>typeof x.hit_rate==='number');const avg=rec.length?rec.reduce((a,x)=>a+Number(x.hit_rate||0),0)/rec.length:null;$('chart-hit').textContent=avg==null?'-':pct(avg);}
function metrics(){const v=(((st.sim||{}).v16||{}).simulation||((st.sim||{}).simulation)||{});$('cabr').textContent=pct(v.cabr_score);$('bst').textContent=pct(v.bst_score);$('cpm').textContent=pct(v.cpm_score);$('cone').textContent=v.cone_width_pips===undefined?'-':`${Number(v.cone_width_pips).toFixed(1)} pips`;$('lot').textContent=v.suggested_lot===undefined?'-':`${Number(v.suggested_lot).toFixed(2)} lot`;$('exec').textContent=v.should_execute?'EXECUTE':'WAIT';$('exec').style.color=v.should_execute?'var(--bull)':'var(--gold)';$('exec-sub').textContent=String(v.execution_reason||'No execution rule available');}
function chart(){const sim=st.sim||{},m=sim.market||{},cand=m.candles||[],v=((sim.v16||{}).simulation||sim.simulation||{}),fc=(sim.final_forecast||{}).points||[],ops=((st.paper||{}).open_positions||[]).filter((x)=>String(x.symbol||'').toUpperCase()===st.symbol),last=cand.length?cand[cand.length-1].timestamp:null;const traces=[{type:'candlestick',x:cand.map(x=>x.timestamp),open:cand.map(x=>x.open),high:cand.map(x=>x.high),low:cand.map(x=>x.low),close:cand.map(x=>x.close),increasing:{line:{color:'#1fcb81'},fillcolor:'#1fcb81'},decreasing:{line:{color:'#ff6b5d'},fillcolor:'#ff6b5d'},name:'Live market'}];const fx=[last].concat(fc.map(x=>x.timestamp||null)),cp=v.consensus_path||[],up=v.cone_upper||[],lo=v.cone_lower||[],mi=v.minority_path||[];if(fc.length&&cp.length===fc.length+1){traces.push({type:'scatter',mode:'lines',x:fx,y:lo,line:{color:'rgba(31,203,129,0)'},hoverinfo:'skip',showlegend:false});traces.push({type:'scatter',mode:'lines',x:fx,y:up,line:{color:'rgba(31,203,129,0)'},fill:'tonexty',fillcolor:'rgba(31,203,129,0.16)',name:'Cone',hoverinfo:'skip'});traces.push({type:'scatter',mode:'lines+markers',x:fx,y:cp,line:{color:v.tier_color||'#f0b54f',width:4},marker:{size:7,color:v.tier_color||'#f0b54f'},name:'Consensus path'});traces.push({type:'scatter',mode:'lines+markers',x:fx.slice(0,mi.length),y:mi,line:{color:'#66bbff',width:2,dash:'dot'},marker:{size:5,color:'#66bbff'},name:'Minority path'});}if(ops.length){traces.push({type:'scatter',mode:'markers+text',x:ops.map(x=>x.entry_time),y:ops.map(x=>x.entry_price),text:ops.map(x=>`${x.direction} ${x.lot} lot`),textposition:'top center',marker:{size:12,color:ops.map(x=>String(x.direction).toUpperCase()==='BUY'?'#1fcb81':'#ff6b5d'),symbol:ops.map(x=>String(x.direction).toUpperCase()==='BUY'?'triangle-up':'triangle-down')},name:'Open paper trades'});}Plotly.react('chart',traces,{paper_bgcolor:'rgba(0,0,0,0)',plot_bgcolor:'rgba(4,17,24,0.25)',font:{color:'#eef6fa',family:'IBM Plex Mono, monospace'},margin:{l:44,r:14,t:16,b:34},hovermode:'x unified',xaxis:{gridcolor:'rgba(255,255,255,0.06)',rangeslider:{visible:false}},yaxis:{gridcolor:'rgba(255,255,255,0.06)'},legend:{orientation:'h',x:0,y:1.08}},{responsive:true,displaylogo:false});}
function sims(){const h=$('sims');h.innerHTML='';const arr=(st.mon||{}).recent_simulations||[];if(!arr.length){h.innerHTML='<div class="item"><strong>No completed simulations yet.</strong><div class="tiny">Once a frozen forecast has real candles after it, hit rate and direction tracking will appear here.</div></div>';return;}for(const x of arr){const n=document.createElement('div');n.className='item';n.innerHTML=`<strong>${String(x.scenario_bias||'-').toUpperCase()} -> ${String(x.realized_direction||'pending').toUpperCase()}</strong><div class="tiny">Tier ${String(x.confidence_tier||'uncertain').toUpperCase()} | cone hit ${x.hit_rate==null?'pending':pct(x.hit_rate)}</div><div class="tiny">Direction ${x.direction_match==null?'pending':x.direction_match?'correct':'wrong'} | minority rescue ${x.minority_was_closer==null?'pending':x.minority_was_closer?'yes':'no'}</div><div class="tiny">${tm(x.anchor_timestamp)}</div>`;h.appendChild(n);}}
function ctx(){const sim=st.sim||{},judge=((sim.swarm_judge||{}).content||{}),jh=$('judge'),fh=$('feeds');jh.innerHTML='';fh.innerHTML='';for(const r of[{t:`Judge stance: ${String(judge.manual_stance||'hold').toUpperCase()}`,d:judge.manual_action_reason||'Manual stance unavailable.'},{t:`Crowd lean: ${judge.crowd_lean||'unknown'}`,d:judge.crowd_emotion||'No crowd emotion summary.'},{t:'Minority case',d:judge.minority_case||'Minority case unavailable.'},{t:'Takeaway',d:judge.judge_summary||judge.discussion_takeaway||'Judge summary unavailable.'}]){const n=document.createElement('div');n.className='item';n.innerHTML=`<strong>${r.t}</strong><div class="tiny">${r.d}</div>`;jh.appendChild(n);}const items=(((sim.feeds||{}).news)||[]).slice(0,4).concat((((sim.feeds||{}).public_discussions)||[]).slice(0,4));if(!items.length){fh.innerHTML='<div class="item"><strong>No live feed items available.</strong><div class="tiny">The simulator still runs even when the sidecar feed is thin.</div></div>';return;}for(const it of items){const n=document.createElement('div');n.className='item';n.innerHTML=`<strong>${it.title||'Untitled feed item'}</strong><div class="tiny">${it.source||'unknown'} | ${tm(it.published_at)}</div>`;fh.appendChild(n);}}
function paper(){const p=st.paper||{},s=p.summary||{};$('pb').textContent=s.balance===undefined?'-':`$${Number(s.balance).toFixed(2)}`;$('pe').textContent=s.equity===undefined?'-':`$${Number(s.equity).toFixed(2)}`;$('pr').textContent=s.realized_pnl===undefined?'-':`$${sgn(s.realized_pnl)}`;$('pr').style.color=Number(s.realized_pnl||0)>=0?'var(--bull)':'var(--bear)';$('pu').textContent=s.unrealized_pnl===undefined?'-':`$${sgn(s.unrealized_pnl)}`;$('pu').style.color=Number(s.unrealized_pnl||0)>=0?'var(--bull)':'var(--bear)';const ob=$('open-body');ob.innerHTML='';const ops=p.open_positions||[];if(!ops.length){ob.innerHTML='<tr><td colspan="6" class="tiny">No open paper positions.</td></tr>';}else for(const x of ops){const r=document.createElement('tr');r.innerHTML=`<td class="mono">${String(x.trade_id||'').slice(0,8)}</td><td style="color:${color(x.direction)};">${x.direction}</td><td>${Number(x.lot||0).toFixed(2)}</td><td>${price(x.entry_price)}</td><td style="color:${Number(x.unrealized_pnl_usd||0)>=0?'var(--bull)':'var(--bear)'};">$${sgn(x.unrealized_pnl_usd)}</td><td><button data-close='${x.trade_id}'>Close</button></td>`;ob.appendChild(r);}const cb=$('closed-body');cb.innerHTML='';const cls=(p.closed_trades||[]).slice().reverse();if(!cls.length){cb.innerHTML='<tr><td colspan="5" class="tiny">No closed trades yet.</td></tr>';}else for(const x of cls){const r=document.createElement('tr');r.innerHTML=`<td>${tm(x.exit_time||x.entry_time)}</td><td>${x.symbol||'-'}</td><td style="color:${color(x.direction)};">${x.direction||'-'}</td><td>${Number(x.lot||0).toFixed(2)}</td><td style="color:${Number(x.pnl_usd||0)>=0?'var(--bull)':'var(--bear)'};">$${sgn(x.pnl_usd)}</td>`;cb.appendChild(r);}ob.querySelectorAll('button[data-close]').forEach((b)=>b.addEventListener('click',async()=>{try{const id=b.getAttribute('data-close'),px=Number((((st.sim||{}).market||{}).current_price)||0);if(!id||!px)return;await j('/api/paper/close',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({trade_id:id,exit_price:px})});await loadPaper();chart();stat(`Closed paper trade ${id}.`);}catch(e){console.error(e);stat(`Paper close failed: ${e.message}`);}}));}
async function loadPaper(){st.paper=await j(`/api/paper/state?symbol=${encodeURIComponent(st.symbol)}`);paper();}
async function refreshMon(){st.mon=await j(`/api/live-monitor?symbol=${encodeURIComponent(st.symbol)}`);sims();head();}
async function run(announce=true){st.symbol=$('symbol').value;st.mode=$('mode').value;st.provider=$('provider').value;st.model=$('model').value.trim();if(announce)stat(`Running ${st.symbol} through the V16 simulator...`);const q=new URLSearchParams({symbol:st.symbol,mode:st.mode,llm_provider:st.provider});if(st.model)q.set('llm_model',st.model);st.sim=await j(`/api/simulate-live?${q.toString()}`);head();metrics();ctx();await refreshMon();await loadPaper();chart();stat(`V16 simulation refreshed for ${st.symbol}.`);}
async function openTrade(){const sim=st.sim||{},m=sim.market||{},v=((sim.v16||{}).simulation||sim.simulation||{}),payload={symbol:st.symbol,direction:$('tdir').value,entry_price:Number(m.current_price||0),confidence_tier:String(v.confidence_tier||'uncertain'),sqt_label:String(((sim.sqt||{}).label)||v.sqt_label||'NEUTRAL'),mode:st.mode,leverage:Number($('tlev').value||200),stop_pips:Number($('tstop').value||20),take_profit_pips:Number($('ttp').value||30),note:$('tnote').value};if(!payload.entry_price){stat('No live price available for paper trading.');return;}await j('/api/paper/open',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});await loadPaper();chart();stat(`Opened ${payload.direction} paper trade on ${payload.symbol}.`);}
async function resetPaper(){await j('/api/paper/reset',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({starting_balance:1000})});await loadPaper();chart();stat('Paper account reset to $1000.');}
function loop(){if(st.timer)clearInterval(st.timer);if($('auto').value!=='on')return;const s=Number($('refresh').value||30);st.timer=setInterval(()=>run(false).catch((e)=>{console.error(e);stat(`Refresh failed: ${e.message}`);}),s*1000);}
$('run').addEventListener('click',()=>run(true).catch((e)=>stat(`Simulation failed: ${e.message}`)));
$('symbol').addEventListener('change',()=>run(true).catch((e)=>stat(`Simulation failed: ${e.message}`)));
$('mode').addEventListener('change',()=>run(true).catch((e)=>stat(`Simulation failed: ${e.message}`)));
$('provider').addEventListener('change',()=>run(true).catch((e)=>stat(`Simulation failed: ${e.message}`)));
$('refresh').addEventListener('change',loop);$('auto').addEventListener('change',loop);
$('open').addEventListener('click',()=>openTrade().catch((e)=>stat(`Paper open failed: ${e.message}`)));
$('reset').addEventListener('click',()=>resetPaper().catch((e)=>stat(`Paper reset failed: ${e.message}`)));
window.addEventListener('load',async()=>{tick();setInterval(tick,1000);try{await loadPaper();await run(false);loop();}catch(e){console.error(e);stat(`Initial load failed: ${e.message}`);}});
</script></div></body></html>
"""
